version: '3.4'

services:
  baselinegraphqlmock:
    image: baselinegraphqlmock
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      BaseLineClient__Address: ${BaseLineClient__Address}
    ports:
      - 4000:4000
