version: '3.4'

services:
  proxy-baseline:
    # image: mazaika/proxy-baseline:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      BaseLineClient__Address: ${BaseLineClient__Address}
    ports:
      - 4000:4000
