enum ScoutEventTypeDTO {
  Goal = 13,
  Assist = 15,
  Violation = 16,
  AwardedPenalty = 19,
  Bullfight = 20,
  Bullies = 22,
  MatchStart = 23,
  PeriodStart = 24,
  MatchEnd = 25,
  PeriodEnd = 26,
  ClassicBullet = 27,
  Occlusion = 28,
  WarmUp = 29,
  BetStop = 30,
  BetStart = 31,
  BulletWin = 32,
  PostMatchBulls = 33,
  GoalieChange = 39,
  Miss = 40,
  MatchCancellation = 41,
  VideoReview = 42,
  Timeout = 43,
  TimerRunning = 44,
  TimerStopping = 45,
  BulletImplemented = 48,
  FirstDeletion = 63,
  SecondDeletion = 64,
  EmptyGoal = 68,
  Goalkeeper = 69,
  TimeOut = 70,
  FreeShot = 71,
  PenaltyShot = 72,
}

export { ScoutEventTypeDTO };
